### ISSUE TITLE
Harden your GitHub account

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-ArtemVasylchuck#1]
Enable 2FA:
* [x] Proceed at https://github.com/settings/security#two-factor-summary
* [ ] If you have a hardware FIDO 2 key/token (like Solo v2 or Yubikey), set it up as a passkey
* [ ] If you have a modern enough phone, set it up as a passkey as well (you may need to use a mobile browser)
* [x] I recommend configuring the following TOTP code generator additionally: https://play.google.com/store/apps/details?id=org.liberty.android.freeotpplus&hl=en_US
  * If you've got a Bitwarden subscription — you can use it instead
  * Don't forget to _securely_ store the recovery codes
  * Pro tip: GitHub now supports passkeys — you can upgrade your FIDO 2 keys to that, including the ones built into your phone.

**Comment by ArtemVasylchuck** [comment]
Added a 2FA via Microsoft Authenticator

**Comment by webknjaz** [comment]
Weird choice but okay. As long as you saved those recovery codes and have backup methods.
